### ISSUE TITLE
Product spec draft 1

### ISSUE THREAD

**Issue by nalaka** [veracity-dev/github-xlsx#1]
- [x] Product spec outline `docs/sad.md`
- [x] Team discussion on product requirements
- [x] Write down in `docs/spec.md` and do a PR
  - [x] Test PR
  - [x] More detail
- [x] Review PR with @nalaka @shanfend @JayanthaPushpaKumara 
- [x] Share a PDF version with full team

**Comment by nalaka** [comment]
Maybe, have a look at https://www.npmjs.com/package/yargs library and nodejs projects using that library

**Comment by nalaka** [comment]
This is what you need to take down:
- What are the main features - just list them down
- Pick a feature and elaborate (write more detail on that)
  - e.g. Since we have a CLI, what is the command we give users to invoke/use this feature
  - What are the options for this parameter?
  - What is the output?
  - What will cause the to fail? What do we do then?

**Comment by ChamudiRW** [comment]
@nalaka @JayanthaPushpaKumara @shanfend We did go through this issue but we didn't figure out exactly what we were supposed to do. @ManuKun forwarded a pull request on it.

**Comment by ManuKun** [comment]
@nalaka @shanfend @JayanthaPushpaKumara 

We updated the  `docs/spec.md` and did a PR #30 .  After reviewing some Documentations and other similar products. 
We used the following links to get a basic idea about the product :

-https://docs.sheetjs.com
-https://www.npmjs.com/package/node-xlsx
-https://github.com/Joshua-rose/github-issues-to-excel/tree/master/src
-https://morioh.com/p/11970299a50b

**Comment by ManuKun** [comment]
Completed all the Tasks !
