### ISSUE TITLE
Setup GitHub CLI tool and Learn basics related to the project

### ISSUE THREAD

**Issue by ChamudiRW** [veracity-dev/github-xlsx#20]
- [x] #23 
- [x] Find examples of typescript programs
- [ ] Get an idea about node.js libraries
  - [ ] CLI args
  - [x] XLSX
  - [ ] GitHub API
- [x] Find how to create a CLI project using node.js

**Comment by ChamudiRW** [comment]
https://cli.github.com/  Is this the GitHub CLI we have to install?   @nalaka @JayanthaPushpaKumara @shanfend

**Comment by nalaka** [comment]
@ChamudiRW - yes

**Comment by nalaka** [comment]
Maybe, have a look at https://www.npmjs.com/package/yargs library and nodejs projects using that library

**Comment by nalaka** [comment]
Team in this tool, we will use some npm libraries to:
- Parse command like arguments and show the CLI menu - e.g. [yargs](https://www.npmjs.com/package/yargs )
- Generate XLSX files - e.g. [node-xlsx](https://www.npmjs.com/package/node-xlsx)
- Interact with the GitHub API - Start exploring in the [official docs](https://developer.github.com/v3/)
-

**Comment by ChamudiRW** [comment]
We did an example calculator project with CLI and Typescript 


We are still working on an example xlxs to Json | json to xlxs product watching tutorials
-also updated the wiki a bit but still working on it


We found a tutorial on how to use yargs but couldn't work on it properly yet

**Comment by ChamudiRW** [comment]
https://www.youtube.com/playlist?list=PLMZdod-kiMhKBxYSWwp7uqHc7zJZbFn I found this tutorial to get started with node.js and there's a video with a tutorial on converting Excel to JSON and JSON to Excel

**Comment by nalaka** [comment]
@ChamudiRW 

> Still couldn't find a proper tutorial on GitHub API but we did learn how to use GitHub CLI

Refer this: https://github.com/octokit/octokit.js#octokit-api-client

We use the API client part

**Comment by nalaka** [comment]
- [ ] Share the PDF and close this issue.
- [ ] Create 2 new issues for 3 examples apps (full Node.js projects)
  - [ ] XLSX and CLI arg parsing (read some option from command line and use it in the XLSX)
  - [ ] Connect to GitHub API and print (in console) a list of issues (or something)
