### ISSUE TITLE
Experiment project xlsx

### ISSUE THREAD

**Issue by ChamudiRW** [veracity-dev/github-xlsx#32]

**Comment by ChamudiRW** [comment]
Referred to a tutorial on "Export data from JavaScript to Excel - Node.js " and managed to create an xlsx file using javascript in my VSCode.  https://www.youtube.com/watch?v=h-7CjLM0HJE

exportService.js file 
```js script

const xlsx = require('xlsx');
const path = require('path');

const exportExcel = (data, workSheetColumnNames, workSheetName, filePath) => {
    const workBook = xlsx.utils.book_new();
    const workSheetData = [
        workSheetColumnNames,
        ... data
    ];
    const workSheet = xlsx.utils.aoa_to_sheet(workSheetData);
    xlsx.utils.book_append_sheet(workBook, workSheet, workSheetName);
    xlsx.writeFile(workBook, path.resolve(filePath));
}

const exportUsersToExcel = (users, workSheetColumnNames, workSheetName, filePath) => {
    const data = users.map(user => {
        return [user.id, user.name, user.age];
    });
    exportExcel(data, workSheetColumnNames, workSheetName, filePath);
}

module.exports = exportUsersToExcel;
```

index.js file
```js script
const exportUsersToExcel = require('./exportService');

const users = [
    {
        id: 0,
        name: 'Peter',
        age: 31
    },
    {
        id: 1,
        name: 'John',
        age: 23
    }
];

const workSheetColumnName = [
    "ID",
    "Name",
    "Age"
]

const workSheetName = 'Users';
const filePath = './outputFiles/excel-from-js.xlsx';

exportUsersToExcel(users, workSheetColumnName, workSheetName, filePath);

```

output: generated an xlsx file with following input
![1](https://user-images.githubusercontent.com/75931718/127365398-6aa96951-f018-4ae5-a91c-2dd6697805bf.PNG)

**Comment by ChamudiRW** [comment]
Is it necessary to convert the code to typescript or we can keep the reference of the above code in Javascript?
@nalaka

**Comment by Keshara1997** [comment]
****Read** Excel Fil**

![1](https://user-images.githubusercontent.com/63952119/127538515-9c3f21ab-2bd8-4650-8a1d-e96a6e2697ad.png)

![2](https://user-images.githubusercontent.com/63952119/127539335-faa94cfa-a4cd-4c40-b40b-dea42bff4ae2.png)

**create data xlsx file**

![3](https://user-images.githubusercontent.com/63952119/127540050-105e5443-d3c8-450d-a415-66d4b68cfbcc.png)

**XLSX **file****
![5](https://user-images.githubusercontent.com/63952119/127550059-50a17f27-630a-4db6-bb94-357f376a993d.png)

Error
![6](https://user-images.githubusercontent.com/63952119/127550662-e4ac4018-384d-4ab2-8e3c-b776deb3daae.png)

**Comment by coolprav** [comment]
we can make a ASCII chart in the CLI by using this lib.. https://www.npmjs.com/package/ascii-table
