### ISSUE TITLE
Experiment project github-api

### ISSUE THREAD

**Issue by ChamudiRW** [veracity-dev/github-xlsx#33]
Projects related to yargs and GitHub CLI

**Comment by ChamudiRW** [comment]
https://www.youtube.com/playlist?list=PL7pEw9n3GkoXZXQpivARUwnOCeqbxPO7r Tried this tutorial series on parsing command line arguments on node.js.

But had an issue in "Using NPM modules & Github Modules Node.js | Part 7 Node Tutorials for Beginners" video at "5:45min" and I couldn't continue from there. 

![1](https://user-images.githubusercontent.com/75931718/127362982-3d3b83be-a5f3-4331-9986-be906748b5de.PNG)

**Comment by coolprav** [comment]
tried to make a github profile finder using github API by watching this link https://www.youtube.com/watch?v=sJspH620ZsU
 got some basic knowledge about dealing with API

1. we need a client and client secret keys to put in our program
2. then call the API via the editor
3. convert API data to JSON
4. we filter the properties from API to get what we want in our program

Is this the API part to our Veracity-dev project issues ? https://api.github.com/repos/veracity-dev/github-xlsx/issues

**Comment by ManuKun** [comment]
I have Tried the Core GitHub REST API Concepts and Created a Wiki page with Examples - [GitHub REST API Starting Guide](https://github.com/veracity-dev/github-xlsx/wiki/GitHub-REST-API-Starting-Guide) to share what I have learned. I will be Updating this Page as I go more deeper into this Concepts.

Page Contains:

1. How to create a Personal Access Token
2. How to get Your own GitHub User Profile
3. How to View Repositories of an authenticated user
4. How to Get Issues assigned to you
5. How to Create a Repository

**Comment by ManuKun** [comment]
I have Created a web app by using Fundamentals of GitHub API. This Web App will ask for Users name and after that will Display all the Repos under that user name.

[Project File](https://github.com/veracity-dev/github-xlsx/tree/33-gh-ex/github-api-%26-web-app)

**Comment by RashaniTharushika** [comment]
I referred tutorials and create a wiki page on How to Import GitHub data to a google sheet by using OAuth App.

https://github.com/veracity-dev/github-xlsx/wiki/Import-GitHub-data-to-a-google-sheet-using-OAuth-app

**Comment by coolprav** [comment]
Working on a project that getting issues by using GitHub API . Follow issues occurred and still figuring it out.

1. need to use token (I was making this without using a Token)
2. found this issue as well
![Screenshot (381)](https://user-images.githubusercontent.com/87390737/127567064-5ff364dd-bd32-413e-8665-415d85fa3c75.png)
![Screenshot (382)](https://user-images.githubusercontent.com/87390737/127567157-97c1fa0b-9c68-4b93-b642-2dfb892c9435.png)

- working on learning how to use parameters - 

- Resources -
 

1. https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests
2. https://docs.github.com/en/rest/reference/issues

**Comment by mathee00** [comment]
Updated the GitHub REST API Starting Guide and fixed the images

Link - https://github.com/veracity-dev/github-xlsx/wiki/GitHub-REST-API-Starting-Guide

**Comment by RashaniTharushika** [comment]
- Learn about Rest API, https://youtu.be/rtWH70_MMHM and some other YouTube videos.

- Referred octokit.js https://github.com/octokit/octokit.js#octokitrest-endpoint-methods.

- Referred videos of building node CLI with Yargs package and tried coding. But below error occurred so couldn't try rest of it.

![Yargs error](https://user-images.githubusercontent.com/79473294/127783018-aefe6729-d171-46b9-8c8d-b61065486c3a.JPG)

**Comment by mathee00** [comment]
Working on [Using APIs in JavaScript - Create a Github Profile Finder Application](https://www.youtube.com/watch?v=sJspH620ZsU) and trying to create a webhook using [ngrok](https://ngrok.com/download) to solve the below issue

<img width="800" alt="Creating token 01" src="https://user-images.githubusercontent.com/59416528/127917695-4f9053ae-c5d1-41fe-bb79-2d7bc540faa1.PNG">


<img width="800" alt="Creating token 02" src="https://user-images.githubusercontent.com/59416528/127917756-20ea6f2d-301e-439f-bcc4-98e4278ae365.PNG">

**Comment by ManuKun** [comment]
I have Created another Example Project on [Exporting GitHub Issues to a csv file using GraphQL API](https://github.com/veracity-dev/github-xlsx/tree/33-gh-ex/github-issues-export). 

Output file (issues.csv) :

![Issues_csv](https://user-images.githubusercontent.com/65827662/127940762-373fa3c1-25d9-4c16-9a4a-81830f3c5197.PNG)

For now I added all the details to be exported into the csv file.
